### ISSUE TITLE
Server will not start

### ISSUE THREAD

**Issue by N0nameHunter** [DBTDerpbox/LEB-ToolBox#12]
Always getting the same error when trying to start the server. Any Ideas?
Starting the server results in this message:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'ViaFabric' (viafabric) 0.4.9+22-main with any version that is compatible with:
		 - minecraft 1.19.2
More details:
	 - Mod 'ViaFabric' (viafabric) 0.4.9+22-main requires any 1.8.x version, version 1.14.4, version 1.15.2, any version between 1.16.4 (inclusive) and 1.17- (exclusive), version 1.17.1, version 1.18.2 or any version between 1.19.3 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.9+22-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.9+22-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.9+22-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.9+22-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.9+22-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)

**Comment by DBTDerpbox** [comment]
as the Readme states, the python version of toolbox is broken and no longer supported, there is a work in progress rewrite you can access from the Java branch

**Comment by N0nameHunter** [comment]
I'm very new to this. Where can I find the Java Branch?

**Comment by N0nameHunter** [comment]
Ok nevermind I found it. But what do I do now? How do I actually execute the Program instead of just opening the folder? I need a tutorial ;-;

**Comment by DBTDerpbox** [comment]
what did you download? the green code button or the download link in the Readme? to make sure we are on the same track this is the branch I'm taking about [https://github.com/Legacy-Edition-Minigames/ToolBox/tree/java](https://github.com/Legacy-Edition-Minigames/ToolBox/tree/java)

**Comment by N0nameHunter** [comment]
Ok I downloaded the Artifacts folder from the readme and extracted it. But when I click on the application (or the jar file) nothig happens.

**Comment by N0nameHunter** [comment]
Correction; A window opens and closes right away

**Comment by DBTDerpbox** [comment]
you need to open it in a terminal
I assume you're using windows

open the start menu and type command prompt and open it, you can use the `cd` command to switch to the folder its in (example: `cd Documents\Toolbox`)

I'll try to give a better guide in a bit when I'm at my pc

once it's in the target folder type `java -jar Toolbox2.0.jar`

**Comment by N0nameHunter** [comment]
Ok It worked. Its currently downloading

**Comment by DBTDerpbox** [comment]
ah great, it should go fine from now

I'll create a batch script for you to open it easier when I have the chance

**Comment by N0nameHunter** [comment]
Lunar client is currently not working, right?

**Comment by N0nameHunter** [comment]
Thank you very much

**Comment by DBTDerpbox** [comment]
> Lunar client is currently not working, right?
> 

currently yeah it doesn't work
been meaning to get around to testing it again as it's received a lot of updates since the "players are invisible" thing happened

**Comment by N0nameHunter** [comment]
I'll probably just use the feather client in the meantime. Again thank you very much. A friend of mine set up the server for us to play just now. Been meaning to try out the good old legacy Battle mode again
